# Generated by Django 2.1.4 on 2018-12-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20181210_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
